spring.application.name=FEp1

server.port=8080

# JSP resolver
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# URL Backend (?úng BE c?a b?n)
be.base-url=http://localhost:8081/api
